import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "@/components/provider/RotationProviders";
import React, { Suspense } from "react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "리그 오브 레전드 정보 앱",
  description: "Generated by create next app",
};

const Loading = React.lazy(() => import("./loading"));

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-100">
        <Header />

        <main className="container mx-auto mt-10 mb-32">
          <Suspense fallback={<Loading />}>
            <Providers>{children}</Providers>
          </Suspense>
        </main>

        <Footer />
      </body>
    </html>
  );
}
